<<<<<<< HEAD
# Generated by Django 3.2.2 on 2021-05-10 13:12
=======
# Generated by Django 3.2 on 2021-05-09 19:46
>>>>>>> cee2b40ffd31001f8d7b39c2186d2a39c5cf711e

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
