# Generated by Django 3.2 on 2021-05-15 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20210510_1312'),
        ('checkout', '0004_auto_20210512_1403'),
    ]

    operations = [
    ]
