# Generated by Django 3.2.3 on 2021-05-16 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210510_1312'),
        ('products', '0005_auto_20210512_1403'),
    ]

    operations = [
    ]
